### ISSUE TITLE
Advertised as Vanilla instead of Vue?

### ISSUE THREAD

**Issue by heyheyhello** [iendeavor/object-visualizer#1]
Hey nice project! I've seen this done in React a few times but it's nice to see something smaller.

I just had a question about the meaning of "vanilla" in the keywords - did you mean able to run alongside any other frameworks? It might to worth clarifying to people that it is embedding a Vue app into their app though. Since the bundle is +300kb and 10000 lines of code where 9700ish are Vue.js. If someone is already using Vue they might not want to load that _twice_. 

Usually "dom" and "vanilla" would mean "uses native DOM APIs and no framework" like http://vanilla-js.com/ :sparkles:  

For people concerned about size there's also an issue building on BundlePhobia https://bundlephobia.com/result?p=object-visualizer but not sure why.

Thanks for sharing a great project

**Comment by iendeavor** [comment]
> I just had a question about the meaning of "vanilla" in the keywords

I removed it, and added vue in the keywords.

> If someone is already using Vue they might not want to load that twice.

I second that. Do I need to replace dependency with peer dependency or build both versions?

> For people concerned about size there's also an issue building on BundlePhobia https://bundlephobia.com/result?p=object-visualizer but not sure why.

😱 I'll try to find out why it is.

Thanks for the comment.

**Comment by heyheyhello** [comment]
Depends on your audience, yeah. Building both versions would target people who are not using Vue and don't care about overhead/bundlesize. It's a nice plug n' play solution they can drop into their HTML. I imagine people _installing_ the package via npm will be using a bundler of somekind so it makes sense to have a peer-dependency so they'll get a log warning on install about needing to install the peer dep themselves - developers already using Vue won't see that message. 

Not sure why bundlephobia is failing 😞

**Comment by iendeavor** [comment]
It seem due to that this project use `esbuild` to build.

**Comment by iendeavor** [comment]
https://github.com/pastelsky/bundlephobia/issues/382

**Comment by iendeavor** [comment]
It looks working well now.
